# --------------------------------
# Limited Creative - Configuration
# Full Default Configuration at:
# https://github.com/possi/LimitedCreative/blob/master/config.yml
#
# (YAML-Syntax: http://en.wikipedia.org/wiki/YAML)
# --------------------------------

store:
    # SeparatedInventoryEnabled
    # Use this option to disable the separated inventories feature, for the case you only need the other features.
    # default: true
    enabled: true
    
    # StoreCreative
    # Should the creative-inventory also be stored on disk, when switching to survival?
    # If disabled, the inventory gets cleared every time on switching to creative.
    # default: true
    creative: true
    
    # UnsafeStore (for storing invalid enchants)
    # By default the new and upgrade-safe storage method for items is used. This method doesn't allow the use
    # of "invalid" enchants, like given by different plugins. Enable it, to allow invalid enchants (not recommended).
    # (May be removed with 1.2, as bukkit then allows unsafed enchants by default)
    # default: false
    unsafe: false
    
    # CreativeArmor
    # When set, all creative Player automatically wears the given items as Armor. So they are better seen by other
    # Players.
    armor:
        # CreativeArmorEnabled
        # When disabled, the players Armor isn't swapped
        # default: true
        enabled: true
        
        # CreativeArmor-Items
        # Allows changing of the "Creative-Armor" to be wear when in creative mode
        # *see Blacklist for details on Item-Types
        head: CHAINMAIL_HELMET
        chest: CHAINMAIL_CHESTPLATE
        legs: CHAINMAIL_LEGGINGS
        feet: CHAINMAIL_BOOTS
    
    # InventoryFolder
    # The folder inside the datadir-folder (plugin/LimitedCreative) where the inventories are saved to.
    # By default the inventories are saved to "plugin/LimitedCreative/inventories".
    # default: "inventories"
    folder: "inventories"
    
    # SeparateAdventureInventory
    # When true, your players get a separate inventory when switching to adventure gamemode (2). Otherwise
    # they have the default survival inventory while in adventure gamemode.
    adventure: false

limit:
    # LimitsEnabled
    # Use this option to disable all drop/pvp/etc. preventions while in creative mode. While you also can get this
    # by giving the "nolimit" permissions, using this option can save you CPU performance.
    # default: true
    enabled: true

    # RemoveDrops
    # When player not allowed to drop items, remove the item instead of putting it back to inventory/quickbar.
    # You may disable this to get rid of the server.log-message: "Fetching addPacket for removed entity: CraftItem"
    # default: true
    remove_drops: true
    
    # BlockPickup
    # Prevents the pickup of items while in creative mode
    # default: false
    pickup: false
    
    # RemovePickup
    # Instead of blocking the pickup, you may want to disappear the item from world (good when destroying walls with
    # signs or playing with minecarts). Only works when BlockPickup: false.
    # The permission nolimit.pickup bypasses the removing.
    # default: false
    remove_pickup: true
    
    # BlockSign
    # Prevents interacting with signs (right-click), while in creative mode, so trading becomes more difficult.
    # Attention: this will also block useful signs, like Lifts.
    # default: true
    sign: true
    
    # BlockButtons
    # When enabled also blocks usage of Buttons & Levers while in creative mode.
    # default: false
    button: false
    
    # BlockWorkbenches
    # When enabled also blocks usage of workbenches like chests (so the creative player never can see his inventar).
    # default: false
    workbench: false
    
    # BlockDamageToMobs
    # Prevents dealing damage to all creatures in creative (friendly sheeps as well as hostile creepers).
    # default: false
    damagemob: false
    
    # UseBlackList
    # Prevents using or placing of the given blocks in creative mode (and only in creative).
    # You can use the technical name (see http://jd.bukkit.org/doxygen/d7/dd9/namespaceorg_1_1bukkit.html#ab7fa290bb19b9a830362aa88028ec80a)
    # or the id of the block/item (better use the id, if you're not sure).
    # To prevent Lava you need to add "LAVA_BUCKET", because lava-blocks aren't "placed", therefore Lava-Buckets are
    # "used".
    # You may add the data separated with a colon e.g.: "35:11" blocks blue wool. But be sure to put it in quotes, to
    # not break yml-configuration! Also supporting Eggs (e.g: "MONSTER_EGG:56" blocks Ghasts-Eggs). If you don't add a
    # data-value, all items/blocks of this material are blocked.
    # You also may add the special block "*" (better add quotes to don't break yml) which prevents the usage of ANY
    # item/block.
    # default: [exp_bottle, bedrock]
    use:
     - EXP_BOTTLE
     - bedrock
    
    # BreakBlackList
    # Prevents destroying of the given blocks in creative mode (and only in creative).
    # You can use the technical name (see http://jd.bukkit.org/doxygen/d7/dd9/namespaceorg_1_1bukkit.html#ab7fa290bb19b9a830362aa88028ec80a)
    # or the id of the block/item (better use the id, if you're not sure).
    # You may add the data separated with a colon e.g.: "WOOL:11" blocks blue wool. But be sure to put it in quotes, to
    # not break yml-configuration! Named data values aren't supported yet. If you don't add a data-value, all blocks
    # of this material are blocked.
    # You also may add the special block "*" (better add quotes to don't break yml) which prevents the breaking of any
    # block.
    # default: [bedrock]
    break:
     - bedrock

region:
    # RegionsEnabled
    # Enables the Feature for "creative-regions". This Feature is automatically disabled, if the required plugin
    # "WorldGuard" (http://dev.bukkit.org/server-mods/worldguard/) isn't found.
    # default: true 
    enabled: true
    
    # RegionOptional
    # Allows Players to use /lc creative|survival to switch between GameModes in creative-regions, even if they
    # have no global permission to those commands
    # default: true
    optional: true
    
    # RegionRememberOptional
    # Remembers if s.o. disables the region gamemode, so the region doesn't change his mode automatically if he enters
    # the region again.
    # Hint: Is very confusing, if MultiVerse "enforce gamemode" swaps your state.
    # default: true
    remember: true

permissions:
    # PermissionsEnabled
    # When enabled, the Permissions will allow selected users to ignore limitations like PvP, Chest-Block, etc.
    # When not enabled, all users are treated equally.
    # Note: Not all Permission, are affected by this option. So you still need the defined permissions or op, to use
    #       commands, even if this options is disabled!
    # default: false
    enabled: false
    
    # PermissionKeepInventory
    # Disables the limitedcreative.keepinventory-Permission, so you can use the separated-inventories-feature, even
    # if you have a permission plugin that grants ALL permission to you.
    # If Enabled, only players WITHOUT the limitedcreative.keepinventory-Permission, have separated inventories;
    # Players with the permission will have the inventory, like this plugin were not installed.
    # When "PermissionsEnabled" is false, the KeepInventory-Option will act like disabled, even if you set it to true.
    # default: false
    keepinventory: false


# Locale (Language)
# Uncomment the "locale: en_US"-Line, to override the locale which be used for localized messages. By default the
# System-Locale is used (selected by Java depending on LC_LANG-Environment-Variable
# default: none (Use System-Default Locale)
#locale: en_US