name: LimitedCreative
main: de.jaschastarke.minecraft.limitedcreative.Core
version: 1.2.5
softdepend: [WorldGuard, WorldEdit, MultiInv]
dev-url: http://dev.bukkit.org/server-mods/limited-creative/
commands:
    limitedcreative:
        description: "LimitedCreative: GameMode-Switch, Creative-Regions, Config"
        aliases: lc
        usage: /<command> - displays LimitedCreative-Help
    /lcr:
        description: "LimitedCreative-Region-Command: configure creative regions"
        aliases: lcregion
        usage: /<command> info|flag [<world>#]<region> - set/get region options
permissions:
    limitedcreative.config:
        description: Allows enabling/disabling of config options ingame
        default: op
    limitedcreative.regions:
        description: Allows usage of the //region commands
        default: op
    limitedcreative.regions.bypass:
        description: Ignores the force of a gamemode, when region optional is disabled
        default: false
    limitedcreative.switch_gamemode:
        description: Allows switching of own game mode to creative and back
        default: op
    limitedcreative.switch_gamemode.backonly:
        description: Allows switching of own game mode to default of the not world he is in, but not back
        default: false
    limitedcreative.switch_gamemode.survival:
        description: Allows switching of own game mode to survival, but not to creative
        default: false
    limitedcreative.switch_gamemode.creative:
        description: Allows switching of own game mode to creative, but not to survival
        default: false
    limitedcreative.switch_gamemode.other:
        description: Allows switching of other users game mode
        default: op
    limitedcreative.keepinventory:
        description: Allows bypassing the inventory separation (if PermissionKeepInventory is enabled in config)
        default: false
    limitedcreative.nolimit.drop:
        description: Allows bypassing the "do not drop anything"-limitation
        default: false
    limitedcreative.nolimit.pickup:
        description: Allows bypassing the "do not pickup anything"-limitation
        default: false
    limitedcreative.nolimit.chest:
        description: Allows bypassing the "do not open a chest"-limitation
        default: false
    limitedcreative.nolimit.sign:
        description: Allows bypassing the "do not interact with signs"-limitation
        default: false
    limitedcreative.nolimit.button:
        description: Allows bypassing the "do not interact with buttons"-limitation
        default: false
    limitedcreative.nolimit.lever:
        description: Allows bypassing the "do not interact with levers"-limitation
        default: false
    limitedcreative.nolimit.pvp:
        description: Allows bypassing the "no pvp"-limitation
        default: false
    limitedcreative.nolimit.mob_damage:
        description: Allows bypassing the "no dealing damage to creatures"-limitation
        default: false
    limitedcreative.nolimit.use:
        description: Allows bypassing the "block place/item use"-limitation
        default: false
    limitedcreative.nolimit.break:
        description: Allows bypassing the "block break"-limitation
        default: false
